[package]
name = "netsly-golang"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.12.1", features = ["v4", "serde"] }
